### ISSUE TITLE
Issue with "space full on device"

### ISSUE THREAD

**Issue by simone-silvestri** [2i2c-org/coessing-image#14]
Hello

we are having an urgent problem with our jupyter hub. 
The space is full and we cannot save files / log in in the hub.
(I am not sure if this is the correct place to write this issue, sorry if it is not)

It seems like there are some deleted "unlinked" files which fill up memory 

```
jovyan@jupyter-silvestri-2esimone0-40gmail-2ecom:~/coessing2022-hub$ df /home/jovyan/
Filesystem                                                       1K-blocks       Used Available Use% Mounted on
10.229.44.234:/homes/coessing/silvestri-2esimone0-40gmail-2ecom 2129505280 2032852992         0 100% /home/jovyan
```

while the output of `du -h /home/jovyan` is
```
172M    /home/jovyan/
jovyan@jupyter-silvestri-2esimone0-40gmail-2ecom:~/coessing2022-hub$ 
```

**Comment by sgibson91** [comment]
Information on how to receive support is here: https://docs.2i2c.org/en/latest/support.html

An email should always be sent to `support@2i2c.org` for greatest visibility and quickest response times

**Comment by simone-silvestri** [comment]
Thank you @sgibson91 will do!

**Comment by damianavila** [comment]
For the record, this is the support ticket: https://2i2c.freshdesk.com/a/tickets/164 and this is the related Slack thread:https://2i2c.slack.com/archives/C028WU9PFBN/p1659360538528229
