### ISSUE TITLE
Add Julia to the environment

### ISSUE THREAD

**Issue by simone-silvestri** [2i2c-org/coessing-image#8]
Hello! If possible I would need a Julia installation for the coessing JupyterHub. 
I think there was an issue open (probably in another repo) but I cannot find it anywhere.

**Comment by sgibson91** [comment]
Hello! We prefer requests like this so come via our support channel (`support@2i2c.org` ; [docs](https://docs.2i2c.org/en/latest/support.html)). This guarantees a response since that channel will always be monitored by the active support steward.

Also, we encourage folk to feel empowered into opening PRs that customise their image as they see fit :) this is so the engineering team don't become bottlenecks on these kinds of requests. See [these docs](https://docs.2i2c.org/en/latest/admin/howto/environment/index.html) for more info

**Comment by consideRatio** [comment]
This is a segment from a jupyterhub user environment image I manage using almost the same base image as used in this projects Dockerfile. For reference, that is available [here](https://github.com/pangeo-data/jupyter-earth/blob/f39927974e4bedf073354038625eb83cd58ea272/hub.jupytearth.org-image/Dockerfile#L117), but below is parts that can be copy pasted into this Dockerfile if one is mindful to do the first part as root and the other part as non-root.

I just looked to provide some quick input about this, good luck!

```Dockerfile
# Install Julia itself (Julia part 1/2)
#
# NOTE: Needs to be followed up by installing the Julia kernel in a location not
#       overridden by mounting the user storage as done below when we are no
#       longer acting as root.
#
# Latest version at https://julialang.org/downloads/
#
ENV JULIA_VERSION 1.7.3
ENV JULIA_PATH /srv/julia
ENV JULIA_DEPOT_PATH ${JULIA_PATH}/pkg
ENV PATH $PATH:${JULIA_PATH}/bin
RUN mkdir -p ${JULIA_PATH} \
 && curl -sSL "https://julialang-s3.julialang.org/bin/linux/x64/${JULIA_VERSION%[.-]*}/julia-${JULIA_VERSION}-linux-x86_64.tar.gz" \
  | tar -xz -C ${JULIA_PATH} --strip-components 1 \
 && mkdir -p ${JULIA_DEPOT_PATH} \
 && chown ${NB_UID}:${NB_UID} ${JULIA_DEPOT_PATH}

# Switch user away from ROOT for the rest
USER ${NB_USER}

# Install Julia kernel (Julia part 2/2)
#
# NOTE: If we are not not setting JUPYTER_DATA_DIR, the Julia kernel gets
#       installed in ~/.local/share/jupyter/kernels, and that folder may be
#       overridden by a home directory mount. This was found out by using
#       "jupyter kernelspec list" during debugging.
#
#       Julia's installkernel function relates to JUPYTER_DATA_DIR via logic
#       defined at https://github.com/JuliaLang/IJulia.jl/blob/cc2a9bf61a2515596b177339f9a3514de8c38573/deps/kspec.jl#L32-L37
#
#       NB_PYTHON_PREFIX is presumed to be /srv/conda/envs/notebook in this
#       case, which is defined in this specific Dockerfile's base image.
#
RUN export JUPYTER_DATA_DIR="$NB_PYTHON_PREFIX/share/jupyter" \
 && julia --eval 'using Pkg; Pkg.add("IJulia"); using IJulia; installkernel("Julia");' \
 && julia --eval 'using Pkg; Pkg.instantiate(); Pkg.resolve(); pkg"precompile"'
```

**Comment by simone-silvestri** [comment]
Thank you for the quick response! I ll try to set it up

**Comment by sgibson91** [comment]
@simone-silvestri I just gave you write access to this repo. If the image builds successfully in your PR (when you open it), then feel free to merge yourself :)

**Comment by simone-silvestri** [comment]
Thanks @consideRatio, your solution seems to work nicely!
